<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="four-wheel_chassis">
    
    <xacro:arg name="use_sim" default="true"/>
    <xacro:arg name="robot_namespace" default="robot1" />
    <xacro:arg name="base_color" default="Black" />
    <xacro:include filename="$(find rc_description)/urdf/rc_r2/omni_wheel.urdf.xacro"/>
    <xacro:include filename="$(find rc_description)/urdf/common/action.urdf.xacro" />
    <!-- <xacro:include filename="$(find urdf01_gazebo)/urdf/omni_chassis/laseer_sensor.xacro" /> -->
    <xacro:property name="roller_type" value="simple" />
    <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
    <xacro:property name="chassis_radius" value="0.36"/>
    <xacro:property name="wheel_offset_z" value="-0.02373"/>
    

    <!-- 底盘 -->
    <link name="base_footprint">
      <visual>
        <geometry>
          <sphere radius="0.001" />
        </geometry>
      </visual>
    </link>

    <joint name="base_link2base_footprint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0 0 0.1" />
    </joint>
    <gazebo reference="base_link">
        <material>Gazebo/$(arg base_color)</material>
    </gazebo>

    <link name="base_link">
    <inertial>
        <origin xyz="0.0168607923484386 0.0118160085012626 -0.336154515273156" rpy="0 0 0" />
        <mass value="7.33831258310109" />
        <inertia
            ixx="0.0140633849923985"
            ixy="1.0018361923056E-11"
            ixz="5.53434626777321E-06"
            iyy="0.0399212998593135"
            iyz="-2.09986324422919E-05"
            izz="0.0267312391673464" />
        </inertial>
    <visual>
        <origin
            xyz="0 0 0"
            rpy="0 0 0" />
        <geometry>
            <mesh
              filename="package://rc_description/meshes/rc_r2/base_link.STL" />
        </geometry>
        <material
            name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
        </material>
    </visual>

    <collision>
        <origin
            xyz="0 0 0"
            rpy="0 0 0" />
        <geometry>
        <mesh
            filename="package://rc_description/meshes/rc_r2/base_link.STL" />
        </geometry>
    </collision>
    </link>

    <xacro:ACTION connected_to="base_link" action_name="location_action" use_sim="$(arg use_sim)" robot_namespace="$(arg robot_namespace)"
                      xyz="-0.035 0 0"
                      rpy="0.0 0.0 0.0"
                      />

    <xacro:omni_wheel prefix="left_front" connected_to="base_link"
                        wheel_x_offset="${chassis_radius/sqrt(2)}" wheel_y_offset="${chassis_radius/sqrt(2)}"
                        wheel_z_offset="${wheel_offset_z}" rotation_degree="${3*pi/4}" roller_type="${roller_type}"
                        max_effort="5" max_velocity="50"
    />
    <xacro:omni_wheel prefix="right_front" connected_to="base_link"
                        wheel_x_offset="${chassis_radius/sqrt(2)}" wheel_y_offset="${-chassis_radius/sqrt(2)}"
                        wheel_z_offset="${wheel_offset_z}" rotation_degree="${pi/4}" roller_type="${roller_type}"
                        max_effort="5" max_velocity="50"
    />
    <xacro:omni_wheel prefix="left_back" connected_to="base_link"
                        wheel_x_offset="${-chassis_radius/sqrt(2)}" wheel_y_offset="${chassis_radius/sqrt(2)}"
                        wheel_z_offset="${wheel_offset_z}" rotation_degree="${-3*pi/4}" roller_type="${roller_type}"
                        max_effort="5" max_velocity="50"
    />
    <xacro:omni_wheel prefix="right_back" connected_to="base_link"
                        wheel_x_offset="${-chassis_radius/sqrt(2)}" wheel_y_offset="${-chassis_radius/sqrt(2)}"
                        wheel_z_offset="${wheel_offset_z}" rotation_degree="${-pi/4}" roller_type="${roller_type}"
                        max_effort="5" max_velocity="50"
    />

    <xacro:wheel_transmission prefix="left_front" mechanical_reduction="-19.2032"/>
    <xacro:wheel_transmission prefix="right_front" mechanical_reduction="-19.2032"/>
    <xacro:wheel_transmission prefix="left_back" mechanical_reduction="-19.2032"/>
    <xacro:wheel_transmission prefix="right_back" mechanical_reduction="-19.2032"/>


    <gazebo>
        <plugin name="rc_ros_control" filename="librc_robot_hw_sim.so">
            <robotNamespace>$(arg robot_namespace)</robotNamespace>
            <robotSimType>rc_gazebo/rcRobotHWSim</robotSimType>
            <publish_tf>false</publish_tf>
        </plugin>
    </gazebo>

</robot>